*codigos_cond_contorno_desloc{
         1        16         1         1         0
       481       496         1         1         0
        16       496        16         1         1
         0
}
*nlvectD{
         1
}
*valores_cond_contorno_desloc{
         1         0         +0.0D0       -6.00D+8
       481         0         +0.0D0       -6.00D+8
        17         2         +0.0D0       -1.20D+9
                             +0.0D0       -1.20D+9
        28        16
         0
}

*nltftnD{
   0
}