*numnp{
	5151
}
*numel{
	5000
}
*nelx{
	50
}
*nely{
	100
}
*nelxReserv{
	50
}
*nelyReserv{
	100
}
*coordenadas_nodais{
         1         4            0.0          100.0
                                0.0            0.0
                             1000.0            0.0
                             1000.0          100.0
        50         1       100        51
         0
}
*conectividades_nodais{
         1         1         1         2        53        52        1  
        50         1         1       100        50        51
         0
}