*codigos_cond_contorno_desloc{
         1        51         1         1         0
      5101      5151         1         1         0
        51      5151        51         1         1
         0
}
*nlvectD{
         1
}
*valores_cond_contorno_desloc{
         1         0         +0.0D0        -2.50D8
      5101         0         +0.0D0        -2.50D8
        52         2         +0.0D0        -5.00D8
                             +0.0D0        -5.00D8
        98        51
         0
}
