*numnp{
	5151
}
*numel{
	5000
}
*nelx{
	100
}
*nely{
	50
}
*nelxReserv{
	100
}
*nelyReserv{
	50
}
*coordenadas_nodais{
         1         8            0.0          100.0
                              100.0            0.0
                              200.0            0.0
                                0.0          200.0
                          70.710678      70.710678
                              150.0            0.0
                          141.42135      141.42135
                                0.0          150.0
       100         1        50       101
         0
}
*conectividades_nodais{
         1         1         1         2       103       102        1  
       100         1         1        50       100       101
         0
}
*conectividades_ladais{
         1         1         1       102       202       101         1
       100         1         1        50       100       201
         0
}