*numnp{
	 496
}
*numel{
	 450
}
*nelx{
	15
}
*nely{
	30
}
*nelxReserv{
	15
}
*nelyReserv{
	30
}
*coordenadas_nodais{
         1         4            0.0          300.0
                                0.0            0.0
                              600.0            0.0
                              600.0          300.0
        15         1        30        16
         0
}
*conectividades_nodais{
         1         1         1         2        18        17        1  
        15         1         1        30        15        16
         0
}