*codigos_cond_contorno_desloc{
         1        16         1         1         0
      1441      1456         1         0         0
         1      1441        16         0         0
        16      1456        16         0         1
         0
}
*nlvectD{
         1
}
*valores_cond_contorno_desloc{
         1         0         +0.0D0     -5.5556D+5
      1441         0         +0.0D0     -5.5555D+5
        17         2         +0.0D0     -1.1111D+6
                             +0.0D0     -1.1111D+6
        88        16
         0
}

*nltftnD{
   1
}

*nptslfD{
   2
}

*gmLoadTimeFunction{
           0.d0           0.d0
           1.d0           1.d0
}