*codigos_cond_contorno_desloc{
         1        16         1         1         0
        16      1456        16         0         1
        16        16         1         1         1
         0
}
*nlvectD{
         1
}
*valores_cond_contorno_desloc{
         1         0         +0.0D0     -2.7778D+6
      1441         0         +0.0D0     -2.7778D+6
        17         2         +0.0D0     -5.5556D+6
                             +0.0D0     -5.5556D+6
        88        16
         0
}

*nltftnD{
   1
}

*nptslfD{
   2
}

*gmLoadTimeFunction{
           0.d0           0.d0
          1.d-3           1.d0
}