*numnp{
    186
}
*numel{
    150
}
*nelx{
	  5
}
*nely{
	30
}
*nelxReserv{
	5
}
*nelyReserv{
	30
}
*coordenadas_nodais{
         1         4            0.0           10.0
                                0.0            0.0
                              100.0            0.0
                              100.0           10.0
         5         1        30         6
         0
}
*conectividades_nodais{
         1         1         1         2         8         7        1  
         5         1         1        30         5         6
         0
}