*numnp{
	15
}
*numel{
	 8
}
*nelx{
	 4
}
*nely{
	2
}
*nelxReserv{
	4
}
*nelyReserv{
	2
}
*coordenadas_nodais{
         1         4            0.0           -1.0
                                4.0           -1.0
                                4.0            1.0
                                0.0            1.0
         4         1         2         5
         0
}
*conectividades_nodais{
         1         1         1         2         7         6         1
         4         1         1         2         4         5
         0
}
*conectividades_ladais{
         1         1         1         6        10         5         1
         4         1         1         2         4         9
         0
}