*codigos_cond_contorno_desloc{
         1        25         1         1         0
      1201      1225         1         1         0
        25      1225        25         1         1
         0
}
*nlvectD{
         1
}
*valores_cond_contorno_desloc{
         1         0         +0.0D0      -50.0D+03
        76         0         +0.0D0      -50.0D+03
        26         2         +0.0D0     -100.0D+03
                             +0.0D0     -100.0D+03
         1        25
         0
}