*numnp{
	1225
}
*numel{
	1152
}
*nelx{
	24
}
*nely{
	48
}
*nelxReserv{
	24
}
*nelyReserv{
	48
}
*coordenadas_nodais{
         1         4            0.0           24.0
                                0.0            0.0
                               48.0            0.0
                               48.0           24.0
        24         1        48        25
         0
}
*conectividades_nodais{
         1         1         1         2        27        26        1  
        24         1         1        48        24        25
         0
}