*codigos_cond_contorno_desloc{
         1      5051       101         1         0
       101      5151       101         1         0
         1       101         1         1         1
         0
}
*nlvectD{
         1
}
*valores_cond_contorno_desloc{
      5051         0         +0.0D0         -9.8D6
      5151         0         +0.0D0         -9.8D6
      5052         2         +0.0D0        -19.6D6
                             +0.0D0        -19.6D6
        98         1
         0
}
