*numnp{
    121
}
*numel{
    100
}
*nelx{
     10
}
*nely{
     10
}
*nelxReserv{
     10
}
*nelyReserv{
     10
}
*coordenadas_nodais{
         1         4            0.0            0.0
                                1.0            0.0
                                1.0            1.0
                                0.0            1.0
        10         1        10        11
         0
}
*conectividades_nodais{
         1         1         1         2        13        12        1
        10         1         1        10        10        11
         0 
}
*conectividades_ladais{
         1         1         1        12        22        11         1
        10         1         1        10        10        21
         0
}