*codigos_cond_contorno_desloc{
         1         1         1         1         1
         2         2         1         1         1
         3         3         1         1         1
         4         4         1         1         1
         5         5         1         1         1
         8         8         1         1         1
         9         9         1         1         1
        12        12         1         1         1
        13        13         1         1         1
        14        14         1         1         1
        15        15         1         1         1
        16        16         1         1         1
         0
}
*nlvectD{
         1
}

*valores_cond_contorno_desloc{
         1         0         6.0e-5         1.2e-4
         2         0         4.0e-5         8.0e-5
         3         0         2.0e-5         4.0e-5
         4         0         0.0e+0         0.0e+0
         5         0         1.4e-4         1.6e-4
         8         0         8.0e-5         4.0e-5
         9         0         2.2e-4         2.0e-4
        12         0         1.6e-4         8.0e-5
        13         0         3.0e-4         2.4e-4
        14         0         2.8e-4         2.0e-4
        15         0         2.6e-4         1.6e-4
        16         0         2.4e-4         1.2e-4
         0
}

*nltftnD{
   1
}

*nptslfD{
   2
}

*gmLoadTimeFunction{
           0.d0           1.d0
          1.d-3           1.d0
}