*read_geoformations_from_elmnt_geoformation{
0
}
*top_post_salt_horizontal_y_axis{
0.12000000E+00
}
*salt_dome_top_horizontal_y_axis{
0.12000000E+00
}
*top_reservoir_horizontal_y_axis{
0.12000000E+00
}
*bottom_reservoir_horizontal_y_axis{
0.00000000E+00
}
*bottom_rift_horizontal_y_axis{
0.00000000E+00
}
*left_reservoir_vertical_x_axis{
0.00000000E+00
}
*right_reservoir_vertical_x_axis{
0.24000000E+00
}
*reference_for_sismic_dome{
0
}

*referenceMap{
|----- top post salt horiz y axis ----------|
|                                           |
|              post_salt_rock               |
|                                           |
|----- salt dome top horiz y axis-----------|
|                                           |
|              saline_cap_rock              |
|                                           |
|------ top reservoir horiz y axis----------|
|              |              |             |
|              L              |             |
|              E              R             |
|    left      F  RESERVOIR   I   right     |
|   burden     T  carbonate   G   burden    |
|    rock      |    rock      H   rock      |
|              |              T             |
|            X axis         X axis          |
|              |              |             |
|----- bottom reservoir horiz y axis -------|
|                                           |
|              RIFT_UNDER_rock              |
|                                           |
|---------- bottom rift horzi y axis--------|

}