*numnp{
    16
}
*numel{
    9
}
*nelx{
	3
}
*nely{
	3
}
*nelxReserv{
	3
}
*nelyReserv{
	3
}
*coordenadas_nodais{
         1         4            0.0         0.12d0
                                0.0            0.0
                             0.24d0            0.0
                             0.24d0         0.12d0
         3         1         3         4
         0
}
*conectividades_nodais{
         1         1         1         2         6         5        1  
         3         1         1         3         3         4
         0
}