*numnp{
	5151
}
*numel{
	5000
}
*nelx{
	100
}
*nely{
	50
}
*nelxReserv{
	100
}
*nelyReserv{
	50
}
*coordenadas_nodais{
         1         4            0.0            0.0
                               48.0           44.0
                               48.0           60.0
                                0.0           44.0
       100         1        50       101
         0
}
*conectividades_nodais{
         1         1         1         2       103       102        1  
       100         1         1        50       100       101
         0
}
*conectividades_ladais{
         1         1         1       102       202       101         1
       100         1         1        50       100       201
         0
}